Verify required outputs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -67,6 +67,18 @@ jobs:
     runs-on: windows-latest
     needs: [create-release-draft]
     steps:
+      - name: Verify Dependencies
+        run: |
+          if [ "${{ needs.create-release-draft.outputs.tag_name }}" = "" ];then
+              echo "Missing required tag name"
+              exit 1
+          fi
+
+          if [ "${{ needs.create-release-draft.outputs.release_id }}" = "" ];then
+              echo "Missing required release ID"
+              exit 1
+          fi
+
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
@@ -111,6 +123,18 @@ jobs:
     runs-on: macos-latest
     needs: [create-release-draft]
     steps:
+      - name: Verify Dependencies
+        run: |
+          if [ "${{ needs.create-release-draft.outputs.tag_name }}" = "" ];then
+              echo "Missing required tag name"
+              exit 1
+          fi
+
+          if [ "${{ needs.create-release-draft.outputs.release_id }}" = "" ];then
+              echo "Missing required release ID"
+              exit 1
+          fi
+
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
@@ -151,6 +175,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: [create-release-draft, release-windows-bundle, release-macos-bundle]
     steps:
+      - name: Verify Dependencies
+        run: |
+          if [ "${{ needs.create-release-draft.outputs.release_id }}" = "" ];then
+              echo "Missing required release ID"
+              exit 1
+          fi
+
       - name: Publish release
         run: |
           curl -f -X PATCH -H "Authorization: token ${{ github.token }}" \
